[workspace]
resolver = "3"
members = ["aerox_ecs", "aerox_logic", "aerox_macro", "aerox_network", "aerox_macro"]

[workspace.dependencies]
anyhow = "=1.0.100"
tokio = { version = "1.47.1", features = ["full"] }
